###
POST http://localhost:3000/register
Content-Type: application/json

{
"email": "labas@krabas.lt",
"password": "secret123"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
"email": "labas@krabas.lt",
"password": "secret123"
}

###
GET http://localhost:3000/article
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1Mjg1NTA3MCwiZXhwIjoxNjUyODY1ODcwfQ.yKLYC3gJx6Vx3U-WlB-TlIgu-P2lZRLtNmoAYL8esfs

###
GET http://localhost:3000/users

###
GET http://localhost:3000/allArticle
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1Mjg1NTA3MCwiZXhwIjoxNjUyODY1ODcwfQ.yKLYC3gJx6Vx3U-WlB-TlIgu-P2lZRLtNmoAYL8esfs
